name: Build Web

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build-web:
    name: Build for Web
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update && sudo apt-get install \
          gnome-desktop-testing libasound2-dev libpulse-dev \
          libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev \
          libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Get Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git --depth=1
          cd emsdk
          ./emsdk install tot
          ./emsdk activate tot

      - name: Set up ninja
        uses: ./.github/actions/setup-ninja

      - name: Build
        run: |
          source emsdk/emsdk_env.sh
          emcmake cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Prepare for upload
        run: |
          mkdir _site
          mv build/bin/card-game.html _site/index.html
          mv build/bin/card-* _site/

      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build-web
    if: startsWith(github.ref, 'refs/tags/v')

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or the latest "vX.X.X" version tag for this action
